export enum LexicalCategory {
    adjective = "adjective",
    adverb = "adverb",
    combiningForm = "combiningForm",
    conjunction = "conjunction",
    contraction = "contraction",
    determiner = "determiner",
    idiomatic = "idiomatic",
    interjection = "interjection",
    noun = "noun",
    numeral = "numeral",
    other = "other",
    particle = "particle",
    predeterminer = "predeterminer",
    prefix = "prefix",
    preposition = "preposition",
    pronoun = "pronoun",
    residual = "residual",
    suffix = "suffix",
    verb = "verb",
}